language: python
# command to install dependencies
install:
  - pip install pytest
  - pip install coverage
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
after_success:
  - coveralls
