language: python
# command to install dependencies
install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt
# command to run tests
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python -c "import sys; print(sys.path)"
  - pytest --cov=cyclic_data test/
after_success:
  - coveralls
